# Generated by Django 3.2.9 on 2021-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.UUIDField(default='24BF4406E7EC494993EB1D32B39B5B2F', editable=False, primary_key=True, serialize=False),
        ),
    ]
