# Generated by Django 3.2.9 on 2021-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.UUIDField(default='B15DC57661B848E9A982AE8F6B3CE2A7', editable=False, primary_key=True, serialize=False),
        ),
    ]
