# Generated by Django 3.2.9 on 2021-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211201_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6D5E8A66F3214C09BAC04CB169D20670', editable=False, max_length=32),
        ),
    ]
