# Generated by Django 3.2.9 on 2021-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20211201_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='7688DC3D6F2A45399AEDAEA03D534761', editable=False, max_length=32),
        ),
    ]
