# Generated by Django 3.2.9 on 2021-12-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_pitch_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name_plural': 'Pitches'},
        ),
    ]
