# Generated by Django 3.2.9 on 2021-12-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_pitches_pitch_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pitch_assign',
        ),
    ]
